server:
  port: 27017
  servlet:
    context-path: /mongodb-tool

spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:123456}@${MONGO_HOST:127.0.0.1}:${MONGO_PORT:27017}/${MONGO_DATABASE:mongo_test}?authSource=${MONGO_AUTH_SOURCE:admin}